import type { CSSProperties } from "react";
import { C } from "./tokens";

export const styles: Record<string, CSSProperties> = {
  stage: {
    position: "relative",
    zIndex: 2,
    width: "100%",
    padding: 20,
    display: "flex",
    justifyContent: "center",
  },
  card: {
    position: "relative",
    zIndex: 2,
    width: "100%",
    maxWidth: 560,
    background: "rgba(255,255,255,0.96)",
    backdropFilter: "blur(18px)",
    borderRadius: 28,
    padding: "34px 30px",
    boxShadow: "0 30px 80px rgba(23,20,60,0.45)",
    border: "1px solid rgba(255,255,255,0.6)",
  },

  brandRow: { display: "flex", alignItems: "center", gap: 12, marginBottom: 26 },
  logoBadge: {
    width: 40,
    height: 40,
    borderRadius: 13,
    display: "grid",
    placeItems: "center",
    background: `linear-gradient(135deg,${C.primary},${C.violet})`,
    flexShrink: 0,
    boxShadow: "0 8px 20px rgba(79,70,229,0.4)",
  },
  brandName: { fontFamily: "var(--font-space)", fontWeight: 700, fontSize: 18, lineHeight: 1.1 },
  brandTag: { fontSize: 12, color: C.muted, marginTop: 2 },

  authTitle: { fontFamily: "var(--font-space)", fontSize: 30, fontWeight: 700, margin: "0 0 6px" },
  authSub: { color: C.muted, fontSize: 15, margin: "0 0 26px", lineHeight: 1.5 },

  googleBtn: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    padding: "15px 18px",
    borderRadius: 15,
    border: "1.5px solid #E5E7EB",
    background: "#fff",
    fontSize: 15.5,
    fontWeight: 600,
    color: "#3C4043",
    cursor: "pointer",
  },
  chooser: { border: "1.5px solid #E5E7EB", borderRadius: 18, padding: 18, background: "#fff" },
  chooserHead: { display: "flex", alignItems: "center", gap: 10, marginBottom: 16 },
  chooserTitle: { fontSize: 15, fontWeight: 600, color: "#3C4043" },
  inputWrap: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "13px 15px",
    border: "1.5px solid #E5E7EB",
    borderRadius: 13,
    marginBottom: 14,
    background: "#F9FAFB",
  },
  emailInput: { flex: 1, border: "none", outline: "none", fontSize: 15, background: "transparent", color: C.ink },

  demoNote: {
    marginTop: 20,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    fontSize: 12.5,
    color: C.muted,
  },
  demoDot: { width: 8, height: 8, borderRadius: "50%", background: "#F59E0B", boxShadow: "0 0 0 4px rgba(245,158,11,.15)" },

  progressWrap: { marginBottom: 26 },
  progressHead: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 10 },
  progressLabel: { fontSize: 12.5, fontWeight: 600, color: C.primary, letterSpacing: 0.3, textTransform: "uppercase" },
  progressTrack: { height: 6, background: C.line, borderRadius: 6, overflow: "hidden" },
  progressFill: {
    height: "100%",
    borderRadius: 6,
    background: `linear-gradient(90deg,${C.primary},${C.violet})`,
    transition: "width .45s cubic-bezier(.4,0,.2,1)",
  },

  stepHead: { display: "flex", gap: 14, alignItems: "flex-start", marginBottom: 22 },
  stepIcon: {
    width: 46,
    height: 46,
    borderRadius: 14,
    flexShrink: 0,
    display: "grid",
    placeItems: "center",
    background: `linear-gradient(135deg,${C.primary}22,${C.violet}22)`,
    color: C.primary,
  },
  stepTitle: { fontFamily: "var(--font-space)", fontSize: 23, fontWeight: 700, margin: 0, lineHeight: 1.2 },
  stepSub: { color: C.muted, fontSize: 14, margin: "5px 0 0", lineHeight: 1.45 },

  ageInput: {
    width: "100%",
    textAlign: "center",
    fontFamily: "var(--font-space)",
    fontSize: 56,
    fontWeight: 700,
    color: C.primary,
    border: "none",
    outline: "none",
    borderBottom: `3px solid ${C.line}`,
    padding: "10px 0",
    background: "transparent",
  },

  nameGrid: { display: "flex", flexDirection: "column", gap: 14 },
  nameInput: {
    width: "100%",
    fontFamily: "var(--font-sans)",
    fontSize: 18,
    fontWeight: 600,
    color: C.ink,
    border: `1.5px solid ${C.line}`,
    outline: "none",
    borderRadius: 13,
    padding: "14px 16px",
    background: "#F9FAFB",
  },

  regionGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(150px,1fr))", gap: 10 },
  regionChip: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    padding: "13px 15px",
    borderRadius: 13,
    border: `1.5px solid ${C.line}`,
    background: "#fff",
    fontSize: 14,
    fontWeight: 600,
    color: C.ink,
    cursor: "pointer",
    textAlign: "left",
  },
  regionChipActive: { borderColor: C.primary, background: `${C.primary}0d`, color: C.primary, boxShadow: `0 0 0 3px ${C.primary}18` },

  searchWrap: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 15px",
    border: `1.5px solid ${C.line}`,
    borderRadius: 13,
    marginBottom: 14,
    background: "#F9FAFB",
  },
  searchInput: { flex: 1, border: "none", outline: "none", fontSize: 14.5, background: "transparent", color: C.ink },

  list: { display: "flex", flexDirection: "column", gap: 8, maxHeight: 340, overflowY: "auto", paddingRight: 4 },
  row: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "13px 14px",
    borderRadius: 13,
    border: `1.5px solid ${C.line}`,
    background: "#fff",
    cursor: "pointer",
    textAlign: "left",
    width: "100%",
  },
  rowActive: { borderColor: C.emerald, background: `${C.emerald}0d`, boxShadow: `0 0 0 3px ${C.emerald}1a` },
  rowText: { flex: 1, fontSize: 14, fontWeight: 600, color: C.ink, lineHeight: 1.35, display: "flex", flexDirection: "column", gap: 3 },
  rowSub: { display: "inline-flex", alignItems: "center", gap: 4, fontSize: 11.5, fontWeight: 500, color: C.muted },
  empty: { padding: "26px 0", textAlign: "center", color: C.muted, fontSize: 14 },

  navRow: { display: "flex", justifyContent: "space-between", gap: 12, marginTop: 26 },
  ghostBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "13px 18px",
    borderRadius: 13,
    border: `1.5px solid ${C.line}`,
    background: "#fff",
    color: C.muted,
    fontSize: 14.5,
    fontWeight: 600,
    cursor: "pointer",
  },
  primaryBtn: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "14px 24px",
    borderRadius: 13,
    border: "none",
    background: `linear-gradient(135deg,${C.primary},${C.violet})`,
    color: "#fff",
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 10px 26px rgba(79,70,229,0.4)",
  },
  btnDisabled: { opacity: 0.42, cursor: "not-allowed", boxShadow: "none" },

  confettiLayer: { position: "fixed", inset: 0, zIndex: 3, pointerEvents: "none", overflow: "hidden" },
  successBadge: {
    width: 88,
    height: 88,
    borderRadius: "50%",
    margin: "0 auto 20px",
    display: "grid",
    placeItems: "center",
    background: `linear-gradient(135deg,${C.emerald},${C.emeraldDark})`,
    boxShadow: "0 16px 40px rgba(16,185,129,0.5)",
  },
  successTitle: {
    fontFamily: "var(--font-space)",
    fontSize: 28,
    fontWeight: 700,
    margin: "0 0 8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  successSub: { color: C.muted, fontSize: 15.5, margin: "0 0 28px", lineHeight: 1.5 },
  holdHint: { fontSize: 13.5, color: C.muted, margin: "0 0 18px", fontWeight: 500 },
  holdCenter: { display: "flex", justifyContent: "center", margin: "6px 0 10px" },
  holdBtn: {
    width: 128,
    height: 128,
    borderRadius: "50%",
    border: "none",
    cursor: "pointer",
    padding: 6,
    display: "grid",
    placeItems: "center",
    touchAction: "none",
    transition: "box-shadow .2s ease",
    userSelect: "none",
  },
  holdInner: {
    width: "100%",
    height: "100%",
    borderRadius: "50%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    background: `linear-gradient(135deg,${C.primary},${C.violet})`,
  },
  holdPct: { color: "#fff", fontFamily: "var(--font-space)", fontWeight: 700, fontSize: 17 },
  holdState: { fontSize: 13.5, fontWeight: 600, marginTop: 12, minHeight: 18 },

  homeStage: { position: "relative", zIndex: 2, width: "100%", minHeight: "100vh" },
  nav: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    padding: "14px 22px",
    margin: 14,
    borderRadius: 18,
    background: "rgba(255,255,255,0.95)",
    backdropFilter: "blur(16px)",
    boxShadow: "0 12px 40px rgba(23,20,60,0.28)",
    flexWrap: "wrap",
  },
  navBrand: { display: "flex", alignItems: "center", gap: 10 },
  navBrandName: { fontFamily: "var(--font-space)", fontWeight: 700, fontSize: 18 },
  navLinks: { display: "flex", gap: 4, flexWrap: "wrap" },
  navLink: {
    padding: "9px 15px",
    borderRadius: 11,
    border: "none",
    background: "transparent",
    color: C.muted,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
  },
  navLinkActive: { background: `${C.primary}12`, color: C.primary },
  navRight: { display: "flex", alignItems: "center", gap: 8 },
  logoutBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "9px 13px",
    borderRadius: 11,
    border: `1.5px solid ${C.line}`,
    background: "#fff",
    color: C.muted,
    fontSize: 13.5,
    fontWeight: 600,
    cursor: "pointer",
  },

  homeInner: { maxWidth: 860, margin: "0 auto", padding: "24px 20px 60px" },
  hero: { textAlign: "center", padding: "34px 20px 28px", color: "#fff" },
  heroGreet: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    padding: "7px 15px",
    borderRadius: 30,
    background: "rgba(255,255,255,0.16)",
    border: "1px solid rgba(255,255,255,0.28)",
    fontSize: 13.5,
    fontWeight: 600,
    marginBottom: 18,
    backdropFilter: "blur(8px)",
  },
  heroTitle: { fontFamily: "var(--font-space)", fontSize: 38, fontWeight: 700, margin: "0 0 12px", lineHeight: 1.15 },
  heroSub: { fontSize: 16, opacity: 0.9, margin: 0, lineHeight: 1.6, maxWidth: 520, marginInline: "auto" },

  infoCard: {
    marginTop: 26,
    background: "rgba(255,255,255,0.97)",
    borderRadius: 24,
    padding: "26px 24px",
    boxShadow: "0 24px 60px rgba(23,20,60,0.35)",
    border: "1px solid rgba(255,255,255,0.6)",
  },
  infoHead: { display: "flex", alignItems: "center", gap: 9, fontFamily: "var(--font-space)", fontSize: 17, fontWeight: 700, marginBottom: 20 },
  infoGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 },
  infoItem: { display: "flex", alignItems: "center", gap: 12, padding: "15px 16px", borderRadius: 15, background: "#F7F7FD", border: `1px solid ${C.line}` },
  infoIcon: { width: 40, height: 40, borderRadius: 12, flexShrink: 0, display: "grid", placeItems: "center", background: `${C.primary}14`, color: C.primary },
  infoLabel: { fontSize: 12, color: C.muted, fontWeight: 600, textTransform: "uppercase", letterSpacing: 0.4 },
  infoValue: { fontSize: 15, fontWeight: 600, color: C.ink, marginTop: 3, lineHeight: 1.3, overflowWrap: "anywhere" },
};

export const rowIcon = (active: boolean): CSSProperties => ({
  width: 34,
  height: 34,
  borderRadius: 10,
  flexShrink: 0,
  display: "grid",
  placeItems: "center",
  background: active ? C.emerald : `${C.primary}14`,
  color: active ? "#fff" : C.primary,
});
